services:
  postgres:
    image: postgres:16-alpine
    container_name: jtube-postgres
    environment:
      POSTGRES_USER: jtube
      POSTGRES_PASSWORD: jtube
      POSTGRES_DB: jtube
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
